name: Build Wasabi File Manager

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate || call venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with PyInstaller
        run: |
          source venv/bin/activate || call venv\Scripts\activate
          pyinstaller --onefile --windowed main.py
      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: wasabi-filemanager-${{ matrix.os }}
          path: dist/ 